#!/usr/bin/env python3
"""
Curve pool indexer — discovers pools from on-chain factories, verifies with fuzz, updates registry.

Usage:
    pip install web3 toml
    python tools/index-pools.py --chain-id 1 --min-tvl 5000000 --max-new 10
    python tools/index-pools.py --chain-id 1 --min-tvl 5000000 --dry-run
"""

import argparse
import json
import os
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path

try:
    import toml
except ImportError:
    sys.exit("pip install toml")

try:
    from web3 import Web3
except ImportError:
    sys.exit("pip install web3")

# ── Factory config per chain ─────────────────────────────────────────────────

FACTORIES = {
    1: [  # Ethereum
        # ── NG factories ────────────────────────────────────────────────
        {
            "address": "0x6A8cbed756804B16E05E741eDaBd5cB544AE21bf",
            "variant": "StableSwapNG",
            "label": "StableSwap-NG",
        },
        {
            "address": "0x98ee851a00abee0d95d08cf4ca2bdce32aeaaf7f",
            "variant": "TwoCryptoNG",
            "label": "TwoCrypto-NG",
        },
        {
            "address": "0x0c0e5f2ff0ff18a3be9b835635039256dc4b4963",
            "variant": "TriCryptoNG",
            "label": "TriCrypto-NG",
        },
        # ── Legacy factories ────────────────────────────────────────────
        {
            "address": "0xB9fC157394Af804a3578134A6585C0dc9cc990d4",
            "variant": "meta_factory",
            "label": "MetaPool Factory (legacy)",
        },
        {
            "address": "0xF18056Bbd320E96A48e3Fbf8bC061322531aac99",
            "variant": "TwoCryptoV1",
            "label": "CryptoSwap Factory (legacy)",
        },
        {
            "address": "0x4F8846Ae9380B90d2E71D5e3D042dff3E7ebb40d",
            "variant": "auto",
            "label": "crvUSD StableSwap Factory",
        },
    ],
}

# ── Minimal ABIs ─────────────────────────────────────────────────────────────

FACTORY_ABI = json.loads('[{"name":"pool_count","outputs":[{"type":"uint256"}],"inputs":[],"stateMutability":"view","type":"function"},{"name":"pool_list","outputs":[{"type":"address"}],"inputs":[{"type":"uint256"}],"stateMutability":"view","type":"function"},{"name":"is_meta","outputs":[{"type":"bool"}],"inputs":[{"type":"address"}],"stateMutability":"view","type":"function"},{"name":"get_base_pool","outputs":[{"type":"address"}],"inputs":[{"type":"address"}],"stateMutability":"view","type":"function"}]')

POOL_ABI = json.loads('[{"name":"coins","outputs":[{"type":"address"}],"inputs":[{"type":"uint256"}],"stateMutability":"view","type":"function"},{"name":"balances","outputs":[{"type":"uint256"}],"inputs":[{"type":"uint256"}],"stateMutability":"view","type":"function"},{"name":"A","outputs":[{"type":"uint256"}],"inputs":[],"stateMutability":"view","type":"function"},{"name":"fee","outputs":[{"type":"uint256"}],"inputs":[],"stateMutability":"view","type":"function"}]')

TOKEN_ABI = json.loads('[{"name":"decimals","outputs":[{"type":"uint8"}],"inputs":[],"stateMutability":"view","type":"function"},{"name":"symbol","outputs":[{"type":"string"}],"inputs":[],"stateMutability":"view","type":"function"}]')

MATH_GETTER_ABI = json.loads('[{"name":"MATH","outputs":[{"type":"address"}],"inputs":[],"stateMutability":"view","type":"function"}]')
VERSION_ABI = json.loads('[{"name":"version","outputs":[{"type":"string"}],"inputs":[],"stateMutability":"view","type":"function"}]')

# ABIs for on-chain variant probing (used by detect_variant_onchain)
GAMMA_ABI = json.loads('[{"name":"gamma","outputs":[{"type":"uint256"}],"inputs":[],"stateMutability":"view","type":"function"}]')
OFFPEG_ABI = json.loads('[{"name":"offpeg_fee_multiplier","outputs":[{"type":"uint256"}],"inputs":[],"stateMutability":"view","type":"function"}]')
STORED_RATES_ABI = json.loads('[{"name":"stored_rates","outputs":[{"type":"uint256[]"}],"inputs":[],"stateMutability":"view","type":"function"}]')
BASE_POOL_ABI = json.loads('[{"name":"base_pool","outputs":[{"type":"address"}],"inputs":[],"stateMutability":"view","type":"function"}]')


def get_rpc_url(chain_id: int) -> str:
    key = f"RPC_URL_{chain_id}"
    url = os.environ.get(key) or os.environ.get("RPC_URL")
    if not url:
        sys.exit(f"{key} or RPC_URL must be set")
    return url


def read_registry(path: Path) -> dict:
    if path.exists():
        return toml.load(path)
    return {"pools": []}


def write_registry(path: Path, registry: dict):
    header = (
        f"# Verified Curve pool registry — Chain ID: {path.stem}\n"
        "#\n"
        "# Auto-generated by tools/index-pools.py. Do not edit manually.\n"
        "#\n"
        "# Every pool with fuzz_verified = true has passed differential fuzz testing\n"
        "# against on-chain get_dy with random swap amounts.\n\n"
    )
    path.parent.mkdir(parents=True, exist_ok=True)
    with open(path, "w") as f:
        f.write(header)
        f.write(toml.dumps(registry))


def _batch_call(w3, calls, block):
    """Execute multiple eth_call in parallel using threading."""
    from concurrent.futures import ThreadPoolExecutor, as_completed
    results = [None] * len(calls)
    def do_call(idx, contract, fn_name, args):
        try:
            fn = getattr(contract.functions, fn_name)(*args)
            return idx, fn.call(block_identifier=block)
        except Exception:
            return idx, None
    with ThreadPoolExecutor(max_workers=20) as pool:
        futures = [pool.submit(do_call, i, c, f, a) for i, (c, f, a) in enumerate(calls)]
        for future in as_completed(futures):
            idx, val = future.result()
            results[idx] = val
    return results


def _probe(w3, addr, abi, fn_name, args=None, block="latest"):
    """Try calling a function on a contract. Returns (True, result) or (False, None)."""
    try:
        c = w3.eth.contract(address=Web3.to_checksum_address(addr), abi=abi)
        fn = getattr(c.functions, fn_name)(*(args or []))
        return True, fn.call(block_identifier=block)
    except Exception:
        return False, None


def detect_variant_onchain(w3, addr, block):
    """Detect pool variant by probing on-chain functions.

    Same logic as tools/detect_variant.py but inlined for use in the indexer.
    Used for factories where the variant isn't known from the factory alone
    (e.g., crvUSD StableSwap Factory).
    """
    has_gamma, _ = _probe(w3, addr, GAMMA_ABI, "gamma", block=block)
    if has_gamma:
        # CryptoSwap — count coins to distinguish TwoCrypto vs TriCrypto
        n_coins = 0
        for i in range(4):
            ok, _ = _probe(w3, addr, POOL_ABI, "coins", [i], block=block)
            if ok:
                n_coins += 1
            else:
                break
        if n_coins == 3:
            return "TriCryptoNG"
        if n_coins == 2:
            has_math, math_addr = _probe(w3, addr, MATH_GETTER_ABI, "MATH", block=block)
            if has_math and math_addr:
                _, version = _probe(w3, math_addr, VERSION_ABI, "version", block=block)
                if version == "v0.1.0":
                    return "TwoCryptoStable"
                return "TwoCryptoNG"
            return "TwoCryptoV1"
        return "TwoCryptoNG"

    has_offpeg, _ = _probe(w3, addr, OFFPEG_ABI, "offpeg_fee_multiplier", block=block)
    if has_offpeg:
        has_stored_rates, _ = _probe(w3, addr, STORED_RATES_ABI, "stored_rates", block=block)
        if has_stored_rates:
            return "StableSwapNG"
        return "StableSwapALend"

    has_base_pool, _ = _probe(w3, addr, BASE_POOL_ABI, "base_pool", block=block)
    if has_base_pool:
        return "StableSwapMeta"

    return "StableSwapV2"


def discover_pools(w3, factory_cfg, existing_addrs, min_tvl, max_new, block):
    """Discover new pools from a factory contract."""
    factory = w3.eth.contract(
        address=Web3.to_checksum_address(factory_cfg["address"]),
        abi=FACTORY_ABI,
    )
    count = factory.functions.pool_count().call(block_identifier=block)
    max_check = min(max_new * 20, count)
    print(f"  {factory_cfg['label']}: {count} pools (checking newest {max_check})")

    # Step 1: batch fetch pool addresses (newest first)
    indices = list(range(count - 1, max(count - 1 - max_check, -1), -1))
    addr_calls = [(factory, "pool_list", [i]) for i in indices]
    pool_addrs = _batch_call(w3, addr_calls, block)

    # Filter out existing
    new_addrs = []
    for addr in pool_addrs:
        if addr and addr.lower() not in existing_addrs:
            new_addrs.append(addr)
    if not new_addrs:
        return []

    # Step 2: batch fetch balance[0] for TVL filter
    pool_contracts = {a: w3.eth.contract(address=a, abi=POOL_ABI) for a in new_addrs}
    bal_calls = [(pool_contracts[a], "balances", [0]) for a in new_addrs]
    bal_results = _batch_call(w3, bal_calls, block)

    # Filter by rough TVL
    tvl_passed = []
    for addr, bal0 in zip(new_addrs, bal_results):
        if bal0 and (bal0 // 10**18) * 3 >= min_tvl:
            tvl_passed.append(addr)
    if not tvl_passed:
        return []

    # Step 3: batch fetch coin details for TVL-passing pools (limit to max_new)
    tvl_passed = tvl_passed[:max_new]
    detail_calls = []
    for addr in tvl_passed:
        pc = pool_contracts[addr]
        for ci in range(4):  # up to 4 coins
            detail_calls.append((pc, "coins", [ci]))
            detail_calls.append((pc, "balances", [ci]))
    detail_results = _batch_call(w3, detail_calls, block)

    # Step 4: batch fetch decimals/symbols for coins
    coin_addrs = {}
    for pi, addr in enumerate(tvl_passed):
        coins_for_pool = []
        for ci in range(4):
            base = pi * 8 + ci * 2
            coin_addr = detail_results[base]
            if coin_addr and coin_addr != "0x" + "0" * 40:
                coins_for_pool.append((coin_addr, detail_results[base + 1]))
        coin_addrs[addr] = coins_for_pool

    # Batch decimals/symbols
    token_calls = []
    token_map = []  # (pool_addr, coin_idx)
    for addr, coins in coin_addrs.items():
        for ci, (coin_addr, _) in enumerate(coins):
            tc = w3.eth.contract(address=coin_addr, abi=TOKEN_ABI)
            token_calls.append((tc, "decimals", []))
            token_calls.append((tc, "symbol", []))
            token_map.append((addr, ci))
    token_results = _batch_call(w3, token_calls, block)

    # Assemble candidates
    token_info = {}
    for ti, (pool_addr, ci) in enumerate(token_map):
        dec = token_results[ti * 2] or 18
        sym = token_results[ti * 2 + 1] or "???"
        if pool_addr not in token_info:
            token_info[pool_addr] = []
        token_info[pool_addr].append((dec, sym))

    # Step 5: For TwoCryptoNG, detect MATH version to distinguish TwoCryptoNG vs TwoCryptoStable
    math_versions = {}
    if factory_cfg["variant"] == "TwoCryptoNG":
        math_calls = [(w3.eth.contract(address=a, abi=MATH_GETTER_ABI), "MATH", []) for a in tvl_passed]
        math_addrs = _batch_call(w3, math_calls, block)
        ver_calls = []
        ver_map = []
        for pool_addr, math_addr in zip(tvl_passed, math_addrs):
            if math_addr:
                ver_calls.append((w3.eth.contract(address=math_addr, abi=VERSION_ABI), "version", []))
                ver_map.append(pool_addr)
        if ver_calls:
            ver_results = _batch_call(w3, ver_calls, block)
            for pool_addr, ver in zip(ver_map, ver_results):
                math_versions[pool_addr] = ver or "unknown"

    candidates = []
    for addr in tvl_passed:
        coins = coin_addrs.get(addr, [])
        info = token_info.get(addr, [])
        if not coins or not info:
            continue
        decimals = [d for d, _ in info]
        symbols = [s for _, s in info]
        balances = [b for _, b in coins]
        tvl = sum(b // 10**d for b, d in zip(balances, decimals) if b)
        if tvl < min_tvl:
            continue

        variant = factory_cfg["variant"]
        # Detect TwoCryptoStable: MATH v0.1.0 = StableSwap math
        if variant == "TwoCryptoNG":
            math_ver = math_versions.get(addr, "v2.0.0")
            if math_ver == "v0.1.0":
                variant = "TwoCryptoStable"
        # MetaPool Factory: ask factory is_meta() to distinguish meta vs plain
        elif variant == "meta_factory":
            try:
                fc = w3.eth.contract(
                    address=Web3.to_checksum_address(factory_cfg["address"]),
                    abi=FACTORY_ABI,
                )
                is_meta = fc.functions.is_meta(Web3.to_checksum_address(addr)).call(block_identifier=block)
                variant = "StableSwapMeta" if is_meta else "StableSwapV2"
            except Exception:
                variant = detect_variant_onchain(w3, addr, block)
        # Auto-detect variant by probing on-chain functions
        elif variant == "auto":
            variant = detect_variant_onchain(w3, addr, block)

        name = "/".join(symbols)
        print(f"    {addr} {name} ({len(coins)}-coin, ~${tvl:,}, {variant})")
        candidates.append({
            "address": addr,
            "variant": variant,
            "name": name,
        })

    return candidates


def verify_pool_quick(w3, pool_entry, block) -> tuple[bool, str]:
    """Quick sanity check: 1 swap, compare on-chain get_dy with our get_amount_out.

    Full fuzz verification happens later in CI when the PR is created.
    This just checks if the variant classification and parameter reading are correct.
    """
    addr = Web3.to_checksum_address(pool_entry["address"])
    variant = pool_entry["variant"]
    pool = w3.eth.contract(address=addr, abi=POOL_ABI)

    # Read balance[0] for a reasonable swap amount (0.1% of balance)
    bal0 = pool.functions.balances(0).call(block_identifier=block)
    dx = max(bal0 // 1000, 1)

    # Get on-chain result
    try:
        if variant.startswith("StableSwap"):
            STABLE_ABI = json.loads('[{"name":"get_dy","outputs":[{"type":"uint256"}],"inputs":[{"type":"int128"},{"type":"int128"},{"type":"uint256"}],"stateMutability":"view","type":"function"}]')
            c = w3.eth.contract(address=addr, abi=STABLE_ABI)
            on_chain = c.functions.get_dy(0, 1, dx).call(block_identifier=block)
        else:
            CRYPTO_ABI = json.loads('[{"name":"get_dy","outputs":[{"type":"uint256"}],"inputs":[{"type":"uint256"},{"type":"uint256"},{"type":"uint256"}],"stateMutability":"view","type":"function"}]')
            c = w3.eth.contract(address=addr, abi=CRYPTO_ABI)
            on_chain = c.functions.get_dy(0, 1, dx).call(block_identifier=block)
    except Exception as e:
        return False, f"on-chain get_dy failed: {e}"

    if on_chain == 0:
        return False, "on-chain get_dy returned 0"

    return True, f"get_dy(0,1,{dx})={on_chain}"


def main():
    parser = argparse.ArgumentParser(description="Curve pool indexer")
    parser.add_argument("--chain-id", type=int, default=1)
    parser.add_argument("--min-tvl", type=int, default=1_000_000, help="Minimum TVL in USD (rough estimate)")
    parser.add_argument("--max-new", type=int, default=10, help="Max new pools to analyze per run")
    parser.add_argument("--dry-run", action="store_true", help="Don't write registry file")
    args = parser.parse_args()

    if args.chain_id not in FACTORIES:
        sys.exit(f"No factory config for chain {args.chain_id}")

    rpc_url = get_rpc_url(args.chain_id)
    w3 = Web3(Web3.HTTPProvider(rpc_url))
    latest = w3.eth.block_number
    block = latest - 5  # use a settled block to avoid inconsistent state
    print(f"Chain {args.chain_id}: block {block} (latest {latest})")

    registry_path = Path(f"registry/{args.chain_id}.toml")
    registry = read_registry(registry_path)
    existing = {p["address"].lower() for p in registry["pools"]}
    print(f"  {len(existing)} existing pools")

    # Discover
    all_candidates = []
    total_factory_pools = 0
    for factory in FACTORIES[args.chain_id]:
        remaining = args.max_new - len(all_candidates)
        if remaining <= 0:
            break
        candidates = discover_pools(w3, factory, existing, args.min_tvl, remaining, block)
        all_candidates.extend(candidates)
        # Count total pools in factory
        fc = w3.eth.contract(address=Web3.to_checksum_address(factory["address"]), abi=FACTORY_ABI)
        total_factory_pools += fc.functions.pool_count().call(block_identifier=block)

    print(f"\n{len(all_candidates)} new candidates above ${args.min_tvl:,} TVL")

    if not all_candidates:
        print("No new pools to add.")
        registry["last_updated"] = datetime.now(timezone.utc).strftime("%Y-%m-%d")
        registry["total_factory_pools"] = total_factory_pools
        if not args.dry_run:
            write_registry(registry_path, registry)
        return

    # Save original pool list for diff
    original_pools = list(registry["pools"])

    # Verify
    verified = 0
    failed = 0
    added_names = []
    skipped_names = []
    for entry in all_candidates:
        print(f"  Checking {entry['name']} ({entry['address']})... ", end="", flush=True)
        ok, msg = verify_pool_quick(w3, entry, block)
        if ok:
            # Pool passes sanity check — add to registry, full fuzz happens in CI on the PR
            print(f"OK ({msg})")
            registry["pools"].append(entry)
            added_names.append(f"{entry['name']} ({entry['address']})")
            verified += 1
        else:
            print(f"SKIP ({msg})")
            skipped_names.append(f"{entry['name']} ({entry['address']}): {msg}")
            failed += 1

    registry["last_updated"] = datetime.now(timezone.utc).strftime("%Y-%m-%d")

    print(f"\nSummary: {verified} added, {failed} skipped")

    if args.dry_run:
        print("(dry run — no files written)")
    elif verified == 0:
        print("No new pools to add.")
        # Update timestamp only
        registry["last_updated"] = datetime.now(timezone.utc).strftime("%Y-%m-%d")
        write_registry(registry_path, registry)
    else:
        # Write new pools to pending file (not main registry)
        # CI will fuzz only these, then merge if passed
        pending_path = Path(f"registry/{args.chain_id}_pending.toml")
        pending_registry = {"pools": [p for p in registry["pools"] if p not in original_pools]}
        write_registry(pending_path, pending_registry)
        print(f"Pending pools written to {pending_path}")

        # Also update main registry (will be committed together)
        registry["last_updated"] = datetime.now(timezone.utc).strftime("%Y-%m-%d")
        registry["total_factory_pools"] = total_factory_pools
        write_registry(registry_path, registry)
        print(f"Registry updated: {registry_path}")

        # Update verified pool count in README
        pool_count = len(registry["pools"])
        update_readme_badge(pool_count, registry["last_updated"], total_factory_pools)

        # Write PR summary for CI
        write_pr_summary(verified, failed, added_names, skipped_names)


def write_pr_summary(verified: int, failed: int, added: list[str], skipped: list[str]):
    """Write PR body summary to .pr-summary.md for CI to pick up."""
    lines = [f"## Pool Registry Update\n"]
    if added:
        lines.append(f"### Added ({verified} pools)\n")
        for name in added:
            lines.append(f"- {name}")
        lines.append("")
    if skipped:
        lines.append(f"### Skipped ({failed} pools)\n")
        for name in skipped:
            lines.append(f"- {name}")
        lines.append("")
    if not added:
        lines.append("No new pools added.\n")
    lines.append(f"\n> Full fuzz verification runs automatically on this PR.")
    Path(".pr-summary.md").write_text("\n".join(lines))
    print(f"PR summary written to .pr-summary.md")


def update_readme_badge(count: int, last_updated: str, total: int = 0):
    """Update the chain status table in README.md."""
    readme = Path("README.md")
    if not readme.exists():
        return
    content = readme.read_text()

    import re
    # Update Ethereum row in chain status table
    pct = (count * 100 // total) if total else 0
    pool_str = f"{count} / {total} ![](https://geps.dev/progress/{pct}?successColor=6366f1)" if total else str(count)
    content = re.sub(
        r'\| Ethereum \|.*\|.*\|.*\|',
        f'| Ethereum | [![Fuzz](https://github.com/sunce86/curve-math/actions/workflows/fuzz-ethereum.yml/badge.svg)](https://github.com/sunce86/curve-math/actions/workflows/fuzz-ethereum.yml) | {pool_str} | {last_updated} |',
        content,
    )
    readme.write_text(content)
    print(f"Updated README: {pool_str} pools, last indexed {last_updated}")


if __name__ == "__main__":
    main()
